modLoader="javafml"
loaderVersion="[36,)"
license="All rights reserved"

[[mods]]
modId="technicu"
version="1.0.7"
displayName="Technicu"
logoFile=""
authors="Kimuna, Kilian51147"
description='''
'''
